### ISSUE TITLE
`Display` for `NSString` truncates at null bytes

### ISSUE THREAD

**Issue by dylni** [nvzqz/fruity#14]
This issue was originally reported privately, but I thought I should create an issue to inform others about it, as it has not yet been fixed.

The implementation of [`Display`](https://doc.rust-lang.org/std/fmt/trait.Display.html) for [`NSString`](https://docs.rs/fruity/0.2.0/fruity/foundation/struct.NSString.html) truncates at null bytes, since it uses [`CStr::from_ptr`](https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.from_ptr). It should be possible to use [`[NSString lengthOfBytesUsingEncoding:]`](https://developer.apple.com/documentation/foundation/nsstring/1410710-lengthofbytesusingencoding) and [`[NSString UTF8String]`](https://developer.apple.com/documentation/foundation/nsstring/1411189-utf8string) instead to create the complete string.

Example:
```rust
let string = NSString::from_str("null\0bytes");
println!("{}", string);
```

That example only prints the string "null". Since [`ToString::to_string`](https://doc.rust-lang.org/std/string/trait.ToString.html#tymethod.to_string) uses [`Display`](https://doc.rust-lang.org/std/fmt/trait.Display.html) to create strings, it has the same issue. [`NSString::to_str`](https://docs.rs/fruity/0.2.0/fruity/foundation/struct.NSString.html#method.to_str) and [`NSString::to_str_with_null`](https://docs.rs/fruity/0.2.0/fruity/foundation/struct.NSString.html#method.to_str_with_nul) also have the same issue.

If you believe this is a valid issue, I encourage you to file a security advisory at https://github.com/rustsec/advisory-db, including a patch version if it is possible to release within two weeks.

Thank you for your work on this crate. Creating a security advisory is not meant to be anything other than a way to provide information to other users.

**Comment by Shnatsel** [comment]
Heads up: this issue has been included in the [RustSec advisory database](https://github.com/RustSec/advisory-db). It will be surfaced by tools such as [cargo-audit](https://github.com/RustSec/cargo-audit) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) from now on.

Once a fix is released to crates.io, please open a pull request to update the advisory with the patched version, or file an issue on [the advisory database repository](https://github.com/RustSec/advisory-db).

**Comment by nvzqz** [comment]
This is now fixed in release `0.3.0`. Sorry for the delay. I cherry-picked it from a series of changes that I wanted to clean up and didn't get around to. I will be adding more APIs and releases soon, with a focus on macOS.

**Comment by dylni** [comment]
Thanks @nvzqz! The new implementation looks good and appears to resolve the issue. Also, [`NSString::from_str_no_copy`](https://docs.rs/fruity/0.3.0/fruity/foundation/struct.NSString.html#method.from_str_no_copy) should no longer need a "Safety" section, since it's safe now.

**Comment by nvzqz** [comment]
@dylni that method is safe because the `NSString` cannot outlive the input due to the `'data` lifetime. I forgot to remove the safety notice.

**Comment by dylni** [comment]
@nvzqz Sorry, I realized my original comment was wrong and edited it. You are correct that the lifetime is now sufficiently enforced.

**Comment by nvzqz** [comment]
No worries. I appreciate your diligence. Things like that do get missed.
